version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ecommerce-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./server
    container_name: ecommerce-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://adityapandeyadu_db_user:<adityapandeyadu>@cluster0.8sq0xyx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=your-super-secret-jwt-key
      - STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    container_name: ecommerce-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_STRIPE_PUBLISHABLE_KEY=pk_test_your_stripe_publishable_key
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongodb_data:
